// Generated by scripts/generate-studio-route-contract.ts. Do not edit by hand.

// prettier-ignore
export const CONTENT_LOCALES = [
  {
    "id": "en",
    "title": "English",
    "prefix": ""
  },
  {
    "id": "fr",
    "title": "Français",
    "prefix": "/fr"
  },
  {
    "id": "es",
    "title": "Español",
    "prefix": "/es"
  },
  {
    "id": "ar",
    "title": "العربية",
    "prefix": "/ar"
  }
] as const

export type ContentLocale = (typeof CONTENT_LOCALES)[number]['id']

// prettier-ignore
export const PAGE_ROUTE_TEMPLATES = {
  "home": {
    "en": "/",
    "fr": "/",
    "es": "/",
    "ar": "/"
  },
  "arc": {
    "en": "/arc",
    "fr": "/arc",
    "es": "/arc",
    "ar": "/arc"
  },
  "capabilities": {
    "en": "/capabilities",
    "fr": "/expertises",
    "es": "/capacidades",
    "ar": "/القدرات"
  },
  "capabilitiesDetail": {
    "en": "/capabilities/in-detail",
    "fr": "/expertises/en-detail",
    "es": "/capacidades/en-detalle",
    "ar": "/القدرات/بالتفصيل"
  },
  "capabilitiesPrograms": {
    "en": "/capabilities/solution-programs",
    "fr": "/expertises/programmes-solutions",
    "es": "/capacidades/programas-de-soluciones",
    "ar": "/القدرات/برامج-الحلول"
  },
  "industries": {
    "en": "/industries",
    "fr": "/secteurs",
    "es": "/sectores",
    "ar": "/القطاعات"
  },
  "about": {
    "en": "/aboutus",
    "fr": "/qui-sommes-nous",
    "es": "/quienes-somos",
    "ar": "/من-نحن"
  },
  "portfolio": {
    "en": "/whoarewe/portfolio",
    "fr": "/qui-sommes-nous/portfolio",
    "es": "/quienes-somos/portfolio",
    "ar": "/من-نحن/أعمالنا"
  },
  "insights": {
    "en": "/insights",
    "fr": "/publications",
    "es": "/publicaciones",
    "ar": "/الرؤى"
  },
  "blog": {
    "en": "/blog",
    "fr": "/blog",
    "es": "/blog",
    "ar": "/المدونة"
  },
  "caseStudies": {
    "en": "/case-studies",
    "fr": "/etudes-de-cas",
    "es": "/casos-de-estudio",
    "ar": "/دراسات-الحالة"
  },
  "news": {
    "en": "/insights/news-articles",
    "fr": "/publications/actualites",
    "es": "/publicaciones/noticias",
    "ar": "/الرؤى/الأخبار"
  },
  "perspectives": {
    "en": "/insights/perspectives",
    "fr": "/publications/perspectives",
    "es": "/publicaciones/perspectivas",
    "ar": "/الرؤى/وجهات-نظر"
  },
  "research": {
    "en": "/insights/research-reports",
    "fr": "/publications/rapports-de-recherche",
    "es": "/publicaciones/informes-de-investigacion",
    "ar": "/الرؤى/تقارير-بحثية"
  },
  "contact": {
    "en": "/contact",
    "fr": "/contact",
    "es": "/contacto",
    "ar": "/تواصل-معنا"
  },
  "privacy": {
    "en": "/privacy-policy",
    "fr": "/politique-de-confidentialite",
    "es": "/politica-de-privacidad",
    "ar": "/سياسة-الخصوصية"
  },
  "cookiePolicy": {
    "en": "/cookie-policy",
    "fr": "/politique-de-cookies",
    "es": "/politica-de-cookies",
    "ar": "/سياسة-ملفات-الارتباط"
  },
  "legal": {
    "en": "/mentions-legales",
    "fr": "/mentions-legales",
    "es": "/avisos-legales",
    "ar": "/إشعارات-قانونية"
  },
  "links": {
    "en": "/links",
    "fr": "/liens",
    "es": "/enlaces",
    "ar": "/روابط"
  },
  "aiAgentsTangier": {
    "en": "/ai-agents-tangier",
    "fr": "/agents-ia-tanger",
    "es": "/agentes-ia-tanger",
    "ar": "/وكلاء-الذكاء-الاصطناعي-طنجة"
  },
  "aiAgentsMorocco": {
    "en": "/ai-agents-morocco",
    "fr": "/agents-ia-maroc",
    "es": "/agentes-ia-marruecos",
    "ar": "/وكلاء-الذكاء-الاصطناعي-المغرب"
  },
  "itConsultingTangier": {
    "en": "/it-consulting-tangier",
    "fr": "/conseil-informatique-tanger",
    "es": "/consultoria-informatica-tanger",
    "ar": "/استشارات-تقنية-طنجة"
  },
  "customSoftwareMorocco": {
    "en": "/custom-software-morocco",
    "fr": "/logiciels-sur-mesure-maroc",
    "es": "/software-a-medida-marruecos",
    "ar": "/برمجيات-مخصصة-المغرب"
  },
  "digitalServicesTangier": {
    "en": "/digital-services-tangier",
    "fr": "/services-digitaux-tanger",
    "es": "/servicios-digitales-tanger",
    "ar": "/خدمات-رقمية-طنجة"
  }
} as const

export type PageRouteKey = keyof typeof PAGE_ROUTE_TEMPLATES

// prettier-ignore
export const DOCUMENT_ROUTE_TEMPLATES = {
  "employeeProfile": {
    "en": "/aboutus/our-people/[slug]",
    "fr": "/qui-sommes-nous/equipe/[slug]",
    "es": "/quienes-somos/equipo/[slug]",
    "ar": "/من-نحن/الفريق/[slug]"
  },
  "caseStudy": {
    "en": "/case-studies/[slug]",
    "fr": "/etudes-de-cas/[slug]",
    "es": "/casos-de-estudio/[slug]",
    "ar": "/دراسات-الحالة/[slug]"
  },
  "capability": {
    "en": "/capabilities/[slug]",
    "fr": "/expertises/[slug]",
    "es": "/capacidades/[slug]",
    "ar": "/القدرات/[slug]"
  },
  "post": {
    "en": "/blog/[slug]",
    "fr": "/blog/[slug]",
    "es": "/blog/[slug]",
    "ar": "/المدونة/[slug]"
  },
  "newsArticle": {
    "en": "/insights/news-articles/[slug]",
    "fr": "/publications/actualites/[slug]",
    "es": "/publicaciones/noticias/[slug]",
    "ar": "/الرؤى/الأخبار/[slug]"
  },
  "perspective": {
    "en": "/insights/perspectives/[slug]",
    "fr": "/publications/perspectives/[slug]",
    "es": "/publicaciones/perspectivas/[slug]",
    "ar": "/الرؤى/وجهات-نظر/[slug]"
  },
  "researchReport": {
    "en": "/insights/research-reports/[slug]",
    "fr": "/publications/rapports-de-recherche/[slug]",
    "es": "/publicaciones/informes-de-investigacion/[slug]",
    "ar": "/الرؤى/تقارير-بحثية/[slug]"
  }
} as const

export type RoutedDocumentType = keyof typeof DOCUMENT_ROUTE_TEMPLATES

export function routeForPage(routeKey: PageRouteKey, locale: ContentLocale) {
  const prefix = CONTENT_LOCALES.find((item) => item.id === locale)?.prefix ?? ''
  const path = PAGE_ROUTE_TEMPLATES[routeKey][locale]
  return `${prefix}${path === '/' ? '' : path}` || '/'
}

export function routeForDocument(type: RoutedDocumentType, locale: ContentLocale, slug: string) {
  const prefix = CONTENT_LOCALES.find((item) => item.id === locale)?.prefix ?? ''
  const template = DOCUMENT_ROUTE_TEMPLATES[type][locale]
  return `${prefix}${template.replace('[slug]', encodeURIComponent(slug))}`
}
