import {writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';

import {LOCALE_PROFILES, PUBLIC_LOCALES} from '../src/i18n/config';
import {ROUTE_MANIFEST} from '../src/i18n/route-manifest';
import {routing, type AppPathname} from '../src/i18n/routing';

const documentRoutes = {
  employeeProfile: {pathname: '/aboutus/our-people/[employee]', parameter: 'employee'},
  caseStudy: {pathname: '/case-studies/[slug]', parameter: 'slug'},
  capability: {pathname: '/capabilities/[slug]', parameter: 'slug'},
  post: {pathname: '/blog/[slug]', parameter: 'slug'},
  newsArticle: {pathname: '/insights/news-articles/[slug]', parameter: 'slug'},
  perspective: {pathname: '/insights/perspectives/[slug]', parameter: 'slug'},
  researchReport: {pathname: '/insights/research-reports/[slug]', parameter: 'slug'},
} as const satisfies Record<string, {pathname: AppPathname; parameter: string}>;

function templatesFor(pathname: AppPathname) {
  const configured = routing.pathnames[pathname];
  return Object.fromEntries(
    PUBLIC_LOCALES.map((locale) => [
      locale,
      typeof configured === 'string' ? configured : configured[locale],
    ]),
  );
}

const contentLocales = PUBLIC_LOCALES.map((locale) => ({
  id: locale,
  title: LOCALE_PROFILES[locale].label,
  prefix: LOCALE_PROFILES[locale].prefix,
}));

const pageRouteTemplates = Object.fromEntries(
  Object.entries(ROUTE_MANIFEST).map(([routeKey, route]) => [
    routeKey,
    templatesFor(route.pathname),
  ]),
);

const documentRouteTemplates = Object.fromEntries(
  Object.entries(documentRoutes).map(([documentType, route]) => [
    documentType,
    Object.fromEntries(
      Object.entries(templatesFor(route.pathname)).map(([locale, template]) => [
        locale,
        template.replace(`[${route.parameter}]`, '[slug]'),
      ]),
    ),
  ]),
);

const output = `// Generated by scripts/generate-studio-route-contract.ts. Do not edit by hand.

// prettier-ignore
export const CONTENT_LOCALES = ${JSON.stringify(contentLocales, null, 2)} as const

export type ContentLocale = (typeof CONTENT_LOCALES)[number]['id']

// prettier-ignore
export const PAGE_ROUTE_TEMPLATES = ${JSON.stringify(pageRouteTemplates, null, 2)} as const

export type PageRouteKey = keyof typeof PAGE_ROUTE_TEMPLATES

// prettier-ignore
export const DOCUMENT_ROUTE_TEMPLATES = ${JSON.stringify(documentRouteTemplates, null, 2)} as const

export type RoutedDocumentType = keyof typeof DOCUMENT_ROUTE_TEMPLATES

export function routeForPage(routeKey: PageRouteKey, locale: ContentLocale) {
  const prefix = CONTENT_LOCALES.find((item) => item.id === locale)?.prefix ?? ''
  const path = PAGE_ROUTE_TEMPLATES[routeKey][locale]
  return \`\${prefix}\${path === '/' ? '' : path}\` || '/'
}

export function routeForDocument(type: RoutedDocumentType, locale: ContentLocale, slug: string) {
  const prefix = CONTENT_LOCALES.find((item) => item.id === locale)?.prefix ?? ''
  const template = DOCUMENT_ROUTE_TEMPLATES[type][locale]
  return \`\${prefix}\${template.replace('[slug]', encodeURIComponent(slug))}\`
}
`;

await writeFile(resolve('studio/content-route-contract.ts'), output, 'utf8');
console.log('Generated studio/content-route-contract.ts from the frontend route manifest.');
